<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="5" failures="3" skipped="0" tests="8" time="38.213" timestamp="2021-09-03T13:01:49.312628" hostname="localhost"><testcase classname="tests.test_issuer_v1" name="test_issue_credential" time="5.556"><error message="failed on setup with &quot;TypeError: 'DID' object is not subscriptable&quot;">yoma_agent_module_scope = &lt;aries_cloudcontroller.acapy_client.AcaPyClient object at 0x7f994dba33a0&gt;

    @pytest.fixture(scope="module")
    async def schema_definition(yoma_agent_module_scope):
        definition = SchemaDefinition(
            name="test_schema", version="0.3", attributes=["speed"]
        )

&gt;       public_did = await create_public_did(yoma_agent_module_scope)

app/tests/test_issuer_v1.py:112:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

aries_agent_controller = &lt;aries_cloudcontroller.acapy_client.AcaPyClient object at 0x7f994dba33a0&gt;

    async def create_public_did(aries_agent_controller):
        generate_did_res = await acapy_wallet_facade.create_did(aries_agent_controller)
&gt;       did_object = generate_did_res["result"]
E       TypeError: 'DID' object is not subscriptable

app/tests/admin/governance/schemas/test_schemas.py:123: TypeError</error></testcase><testcase classname="tests.test_issuer_v1" name="test_offer_credential" time="0.001"><error message="failed on setup with &quot;TypeError: 'DID' object is not subscriptable&quot;">yoma_agent_module_scope = &lt;aries_cloudcontroller.acapy_client.AcaPyClient object at 0x7f994dba33a0&gt;

    @pytest.fixture(scope="module")
    async def schema_definition(yoma_agent_module_scope):
        definition = SchemaDefinition(
            name="test_schema", version="0.3", attributes=["speed"]
        )

&gt;       public_did = await create_public_did(yoma_agent_module_scope)

app/tests/test_issuer_v1.py:112:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

aries_agent_controller = &lt;aries_cloudcontroller.acapy_client.AcaPyClient object at 0x7f994dba33a0&gt;

    async def create_public_did(aries_agent_controller):
        generate_did_res = await acapy_wallet_facade.create_did(aries_agent_controller)
&gt;       did_object = generate_did_res["result"]
E       TypeError: 'DID' object is not subscriptable

app/tests/admin/governance/schemas/test_schemas.py:123: TypeError</error></testcase><testcase classname="tests.test_issuer_v1" name="test_get_x_record" time="21.273"><error message="failed on setup with &quot;TypeError: 'DID' object is not subscriptable&quot;">yoma_agent_module_scope = &lt;aries_cloudcontroller.acapy_client.AcaPyClient object at 0x7f994dba33a0&gt;

    @pytest.fixture(scope="module")
    async def schema_definition(yoma_agent_module_scope):
        definition = SchemaDefinition(
            name="test_schema", version="0.3", attributes=["speed"]
        )

&gt;       public_did = await create_public_did(yoma_agent_module_scope)

app/tests/test_issuer_v1.py:112:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

aries_agent_controller = &lt;aries_cloudcontroller.acapy_client.AcaPyClient object at 0x7f994dba33a0&gt;

    async def create_public_did(aries_agent_controller):
        generate_did_res = await acapy_wallet_facade.create_did(aries_agent_controller)
&gt;       did_object = generate_did_res["result"]
E       TypeError: 'DID' object is not subscriptable

app/tests/admin/governance/schemas/test_schemas.py:123: TypeError</error></testcase><testcase classname="tests.test_issuer_v1" name="test_get_records" time="0.013"><failure message="AttributeError: 'AcaPyClient' object has no attribute 'issuer_credential_v1_0'">async_client_alice_module_scope = &lt;httpx.AsyncClient object at 0x7f994da8bac0&gt;

    @pytest.mark.asyncio
    async def test_get_records(async_client_alice_module_scope):
&gt;       records = (await async_client_alice_module_scope.get(BASE_PATH + "/records")).json()

app/tests/test_issuer_v1.py:259:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../.venv-fastapi/lib/python3.8/site-packages/httpx/_client.py:1661: in get
    return await self.request(
../.venv-fastapi/lib/python3.8/site-packages/httpx/_client.py:1425: in request
    response = await self.send(
../.venv-fastapi/lib/python3.8/site-packages/httpx/_client.py:1510: in send
    response = await self._send_handling_auth(
../.venv-fastapi/lib/python3.8/site-packages/httpx/_client.py:1545: in _send_handling_auth
    response = await self._send_handling_redirects(
../.venv-fastapi/lib/python3.8/site-packages/httpx/_client.py:1579: in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
../.venv-fastapi/lib/python3.8/site-packages/httpx/_client.py:1620: in _send_single_request
    ) = await transport.handle_async_request(
../.venv-fastapi/lib/python3.8/site-packages/httpx/_transports/asgi.py:157: in handle_async_request
    await self.app(scope, receive, send)
../.venv-fastapi/lib/python3.8/site-packages/fastapi/applications.py:199: in __call__
    await super().__call__(scope, receive, send)
../.venv-fastapi/lib/python3.8/site-packages/starlette/applications.py:112: in __call__
    await self.middleware_stack(scope, receive, send)
../.venv-fastapi/lib/python3.8/site-packages/starlette/middleware/errors.py:181: in __call__
    raise exc from None
../.venv-fastapi/lib/python3.8/site-packages/starlette/middleware/errors.py:159: in __call__
    await self.app(scope, receive, _send)
../.venv-fastapi/lib/python3.8/site-packages/starlette/exceptions.py:82: in __call__
    raise exc from None
../.venv-fastapi/lib/python3.8/site-packages/starlette/exceptions.py:71: in __call__
    await self.app(scope, receive, sender)
../.venv-fastapi/lib/python3.8/site-packages/starlette/routing.py:580: in __call__
    await route.handle(scope, receive, send)
../.venv-fastapi/lib/python3.8/site-packages/starlette/routing.py:241: in handle
    await self.app(scope, receive, send)
../.venv-fastapi/lib/python3.8/site-packages/starlette/routing.py:52: in app
    response = await func(request)
../.venv-fastapi/lib/python3.8/site-packages/fastapi/routing.py:214: in app
    raw_response = await run_endpoint_function(
../.venv-fastapi/lib/python3.8/site-packages/fastapi/routing.py:149: in run_endpoint_function
    return await dependant.call(**values)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

aries_controller = &lt;aries_cloudcontroller.acapy_client.AcaPyClient object at 0x7f994db01b20&gt;

    @router.get("/records", response_model=V10CredentialExchangeListResult)
    async def get_records(
        aries_controller: AcaPyClient = Depends(agent_selector),
    ):
        """
        Get list of records.
        """
&gt;       return await aries_controller.issuer_credential_v1_0.get_records()
E       AttributeError: 'AcaPyClient' object has no attribute 'issuer_credential_v1_0'

app/generic/issuers_v1.py:121: AttributeError</failure></testcase><testcase classname="tests.test_issuer_v1" name="test_send_credential_request" time="10.015"><failure message="AttributeError: 'AcaPyClient' object has no attribute 'issuer_credential_v1_0'">async_client_bob_module_scope = &lt;httpx.AsyncClient object at 0x7f994eca4460&gt;

    @pytest.mark.asyncio
    async def test_send_credential_request(async_client_bob_module_scope):
        # TODO check for the successful request
        time.sleep(10)
        cred_send_res = (
&gt;           await async_client_bob_module_scope.post(
                BASE_PATH + f"/credential/request?credential_x_id={CRED_X_ID}"
            )
        ).json()

app/tests/test_issuer_v1.py:270:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../.venv-fastapi/lib/python3.8/site-packages/httpx/_client.py:1746: in post
    return await self.request(
../.venv-fastapi/lib/python3.8/site-packages/httpx/_client.py:1425: in request
    response = await self.send(
../.venv-fastapi/lib/python3.8/site-packages/httpx/_client.py:1510: in send
    response = await self._send_handling_auth(
../.venv-fastapi/lib/python3.8/site-packages/httpx/_client.py:1545: in _send_handling_auth
    response = await self._send_handling_redirects(
../.venv-fastapi/lib/python3.8/site-packages/httpx/_client.py:1579: in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
../.venv-fastapi/lib/python3.8/site-packages/httpx/_client.py:1620: in _send_single_request
    ) = await transport.handle_async_request(
../.venv-fastapi/lib/python3.8/site-packages/httpx/_transports/asgi.py:157: in handle_async_request
    await self.app(scope, receive, send)
../.venv-fastapi/lib/python3.8/site-packages/fastapi/applications.py:199: in __call__
    await super().__call__(scope, receive, send)
../.venv-fastapi/lib/python3.8/site-packages/starlette/applications.py:112: in __call__
    await self.middleware_stack(scope, receive, send)
../.venv-fastapi/lib/python3.8/site-packages/starlette/middleware/errors.py:181: in __call__
    raise exc from None
../.venv-fastapi/lib/python3.8/site-packages/starlette/middleware/errors.py:159: in __call__
    await self.app(scope, receive, _send)
../.venv-fastapi/lib/python3.8/site-packages/starlette/exceptions.py:82: in __call__
    raise exc from None
../.venv-fastapi/lib/python3.8/site-packages/starlette/exceptions.py:71: in __call__
    await self.app(scope, receive, sender)
../.venv-fastapi/lib/python3.8/site-packages/starlette/routing.py:580: in __call__
    await route.handle(scope, receive, send)
../.venv-fastapi/lib/python3.8/site-packages/starlette/routing.py:241: in handle
    await self.app(scope, receive, send)
../.venv-fastapi/lib/python3.8/site-packages/starlette/routing.py:52: in app
    response = await func(request)
../.venv-fastapi/lib/python3.8/site-packages/fastapi/routing.py:214: in app
    raw_response = await run_endpoint_function(
../.venv-fastapi/lib/python3.8/site-packages/fastapi/routing.py:149: in run_endpoint_function
    return await dependant.call(**values)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

credential_x_id = '', aries_controller = &lt;aries_cloudcontroller.acapy_client.AcaPyClient object at 0x7f994d859070&gt;

    @router.post("/credential/request", response_model=V10CredentialExchange)
    async def send_credential_request(
        credential_x_id: str,
        aries_controller: AcaPyClient = Depends(agent_selector),
    ):
        """
        Send credential request.

        Parameters:
        -----------
        credential_helper: CredentialHelper
            payload for sending a credential request

        Returns:
        --------
            The response object obtained from sending a credential offer.
        """
&gt;       return await aries_controller.issuer_credential_v1_0.send_request(credential_x_id)
E       AttributeError: 'AcaPyClient' object has no attribute 'issuer_credential_v1_0'

app/generic/issuers_v1.py:226: AttributeError</failure></testcase><testcase classname="tests.test_issuer_v1" name="test_store_credential" time="0.001"><error message="failed on setup with &quot;TypeError: 'DID' object is not subscriptable&quot;">yoma_agent_module_scope = &lt;aries_cloudcontroller.acapy_client.AcaPyClient object at 0x7f994dba33a0&gt;

    @pytest.fixture(scope="module")
    async def schema_definition(yoma_agent_module_scope):
        definition = SchemaDefinition(
            name="test_schema", version="0.3", attributes=["speed"]
        )

&gt;       public_did = await create_public_did(yoma_agent_module_scope)

app/tests/test_issuer_v1.py:112:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

aries_agent_controller = &lt;aries_cloudcontroller.acapy_client.AcaPyClient object at 0x7f994dba33a0&gt;

    async def create_public_did(aries_agent_controller):
        generate_did_res = await acapy_wallet_facade.create_did(aries_agent_controller)
&gt;       did_object = generate_did_res["result"]
E       TypeError: 'DID' object is not subscriptable

app/tests/admin/governance/schemas/test_schemas.py:123: TypeError</error></testcase><testcase classname="tests.test_issuer_v1" name="test_send_proposal" time="0.001"><error message="failed on setup with &quot;TypeError: 'DID' object is not subscriptable&quot;">yoma_agent_module_scope = &lt;aries_cloudcontroller.acapy_client.AcaPyClient object at 0x7f994dba33a0&gt;

    @pytest.fixture(scope="module")
    async def schema_definition(yoma_agent_module_scope):
        definition = SchemaDefinition(
            name="test_schema", version="0.3", attributes=["speed"]
        )

&gt;       public_did = await create_public_did(yoma_agent_module_scope)

app/tests/test_issuer_v1.py:112:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

aries_agent_controller = &lt;aries_cloudcontroller.acapy_client.AcaPyClient object at 0x7f994dba33a0&gt;

    async def create_public_did(aries_agent_controller):
        generate_did_res = await acapy_wallet_facade.create_did(aries_agent_controller)
&gt;       did_object = generate_did_res["result"]
E       TypeError: 'DID' object is not subscriptable

app/tests/admin/governance/schemas/test_schemas.py:123: TypeError</error></testcase><testcase classname="tests.test_issuer_v1" name="test_send_problem_report" time="0.021"><failure message="AttributeError: 'AcaPyClient' object has no attribute 'issuer_credential_v1_0'">async_client_bob_module_scope = &lt;httpx.AsyncClient object at 0x7f994eca4460&gt;

    @pytest.mark.asyncio
    async def test_send_problem_report(async_client_bob_module_scope):
        # TODO check for the correct response when state is credential_received
        cred_store_res = (
&gt;           await async_client_bob_module_scope.post(
                BASE_PATH + f"/problem-report?credential_x_id={CRED_X_ID}",
                data=json.dumps({"description": "Problem"}),
            )
        ).json()

app/tests/test_issuer_v1.py:321:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../.venv-fastapi/lib/python3.8/site-packages/httpx/_client.py:1746: in post
    return await self.request(
../.venv-fastapi/lib/python3.8/site-packages/httpx/_client.py:1425: in request
    response = await self.send(
../.venv-fastapi/lib/python3.8/site-packages/httpx/_client.py:1510: in send
    response = await self._send_handling_auth(
../.venv-fastapi/lib/python3.8/site-packages/httpx/_client.py:1545: in _send_handling_auth
    response = await self._send_handling_redirects(
../.venv-fastapi/lib/python3.8/site-packages/httpx/_client.py:1579: in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
../.venv-fastapi/lib/python3.8/site-packages/httpx/_client.py:1620: in _send_single_request
    ) = await transport.handle_async_request(
../.venv-fastapi/lib/python3.8/site-packages/httpx/_transports/asgi.py:157: in handle_async_request
    await self.app(scope, receive, send)
../.venv-fastapi/lib/python3.8/site-packages/fastapi/applications.py:199: in __call__
    await super().__call__(scope, receive, send)
../.venv-fastapi/lib/python3.8/site-packages/starlette/applications.py:112: in __call__
    await self.middleware_stack(scope, receive, send)
../.venv-fastapi/lib/python3.8/site-packages/starlette/middleware/errors.py:181: in __call__
    raise exc from None
../.venv-fastapi/lib/python3.8/site-packages/starlette/middleware/errors.py:159: in __call__
    await self.app(scope, receive, _send)
../.venv-fastapi/lib/python3.8/site-packages/starlette/exceptions.py:82: in __call__
    raise exc from None
../.venv-fastapi/lib/python3.8/site-packages/starlette/exceptions.py:71: in __call__
    await self.app(scope, receive, sender)
../.venv-fastapi/lib/python3.8/site-packages/starlette/routing.py:580: in __call__
    await route.handle(scope, receive, send)
../.venv-fastapi/lib/python3.8/site-packages/starlette/routing.py:241: in handle
    await self.app(scope, receive, send)
../.venv-fastapi/lib/python3.8/site-packages/starlette/routing.py:52: in app
    response = await func(request)
../.venv-fastapi/lib/python3.8/site-packages/fastapi/routing.py:214: in app
    raw_response = await run_endpoint_function(
../.venv-fastapi/lib/python3.8/site-packages/fastapi/routing.py:149: in run_endpoint_function
    return await dependant.call(**values)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

explanation = {'description': 'Problem'}, credential_x_id = ''
aries_controller = &lt;aries_cloudcontroller.acapy_client.AcaPyClient object at 0x7f994ed46ca0&gt;

    @router.post("/problem-report", response_model=V10CredentialProblemReportRequest)
    async def problem_report(
        explanation: dict,
        credential_x_id: str,
        aries_controller: AcaPyClient = Depends(agent_selector),
    ):

        """
        Create problem report for record.

        Parameters:
        -----------
        explanation: dict
        credential_x_id: str
            credential exchange id
        """
&gt;       return await aries_controller.issuer_credential_v1_0.send_problem_report(
            credential_x_id, explanation=explanation["description"]
        )
E       AttributeError: 'AcaPyClient' object has no attribute 'issuer_credential_v1_0'

app/generic/issuers_v1.py:179: AttributeError</failure></testcase></testsuite></testsuites>